export const GRID_DATA_LOAD = 'GRID_DATA_LOAD';
export const GRID_SELECT_ROW = 'GRID_SELECT_ROW';
export const GRID_INSERT_ROW = 'GRID_INSERT_ROW';
export const GRID_REFRESH_ROWS = 'GRID_REFRESH_ROWS';
export const GRID_FILTERED_ROWS = 'GRID_FILTERED_ROWS';
export const GRID_SELECT_ROW_CLEAN = 'GRID_SELECT_ROW_CLEAN';
