// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2-devel
// 	protoc        v5.27.1
// source: folders.proto

package folders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Folders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Root     *bool      `protobuf:"varint,2,opt,name=root,proto3,oneof" json:"root,omitempty"`
	Children []*Folders `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *Folders) Reset() {
	*x = Folders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_folders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Folders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Folders) ProtoMessage() {}

func (x *Folders) ProtoReflect() protoreflect.Message {
	mi := &file_folders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Folders.ProtoReflect.Descriptor instead.
func (*Folders) Descriptor() ([]byte, []int) {
	return file_folders_proto_rawDescGZIP(), []int{0}
}

func (x *Folders) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Folders) GetRoot() bool {
	if x != nil && x.Root != nil {
		return *x.Root
	}
	return false
}

func (x *Folders) GetChildren() []*Folders {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_folders_proto protoreflect.FileDescriptor

var file_folders_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x69, 0x0a, 0x07, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x00, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x08,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_folders_proto_rawDescOnce sync.Once
	file_folders_proto_rawDescData = file_folders_proto_rawDesc
)

func file_folders_proto_rawDescGZIP() []byte {
	file_folders_proto_rawDescOnce.Do(func() {
		file_folders_proto_rawDescData = protoimpl.X.CompressGZIP(file_folders_proto_rawDescData)
	})
	return file_folders_proto_rawDescData
}

var file_folders_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_folders_proto_goTypes = []any{
	(*Folders)(nil), // 0: api.Folders
}
var file_folders_proto_depIdxs = []int32{
	0, // 0: api.Folders.children:type_name -> api.Folders
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_folders_proto_init() }
func file_folders_proto_init() {
	if File_folders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_folders_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Folders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_folders_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_folders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_folders_proto_goTypes,
		DependencyIndexes: file_folders_proto_depIdxs,
		MessageInfos:      file_folders_proto_msgTypes,
	}.Build()
	File_folders_proto = out.File
	file_folders_proto_rawDesc = nil
	file_folders_proto_goTypes = nil
	file_folders_proto_depIdxs = nil
}
